name: PR tests (gcc-5, ubuntu, mpich, kokkos)

on: [pull_request]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Build the Docker image
      run: docker build . --file --build-arg KOKKOS_ENABLED=1 Dockerfile-ubuntu --tag vt:$(date +%s)
